### ISSUE TITLE
Variable names consume the underline on the deprecated class/function

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/pyls-memestra#25]
Like the picture:

![image](https://user-images.githubusercontent.com/17600982/93240698-fd3aa480-f773-11ea-8994-ec70d4e44020.png)

If the variable name is too big the underline disappears completely.
I'd expect it to be a bug in Jupyter-LSP or the palantir PLS.

@SylvainCorlay just so you can be aware.

**Comment by SylvainCorlay** [comment]
I think this is a display issue with jupyterlab-lsp
