### ISSUE TITLE
Allow users to configure the deprecation decorators

### ISSUE THREAD

**Issue by marimeireles** [QuantStack/pyls-memestra#26]
We don't have a way to change the default decorator now. Unless the user manually:

1. Build pyls-memestra with the dev installation in your system
2. Go to https://github.com/QuantStack/pyls-memestra/blob/943130b68a403e21f64d7671b70c7e365caff1cf/pyls_memestra/plugin.py#L8 and change it to the name of the package you're using + the wrapper, if needed please see https://memestra.readthedocs.io/en/latest/

**Comment by marimeireles** [comment]
@SylvainCorlay we have to fix this eventually. Any ideas on how to allow users to change this?
I'd be thankful for any insights, couldn't think of anything.

**Comment by SylvainCorlay** [comment]
Yes, I think that decorators could be read from a configuration file eventually.

Just making ` deprecated_uses = memestra(code, decorator=MEMESTRA_DECORATORS)`  where ``MEMESTRA_DRECORATORS` would be set to `("decoratortest", "deprecated"))` at the top of the file, and later on read from a configuration file upon loading the module may be good enough.

**Comment by marimeireles** [comment]
Closed by #31
