### ISSUE TITLE
Use `DiagnosticTag.Deprecated`

### ISSUE THREAD

**Issue by krassowski** [QuantStack/pyls-memestra#52]
LSP 3.15 enables special treatment of diagnostics for deprecated code using [`DiagnosticTag`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#diagnosticTag)s. By adding `"tags": [2]` you can tell the clients that the code is deprecated and the client can decorate it with strike-through. I am in a bit of a chicken and egg problem writing tests for this feature for JupyterLab-LSP (https://github.com/jupyter-lsp/jupyterlab-lsp/pull/736) because most servers do not provide it yet; I thought it might be a good idea to implement if in pylsp-memestra early and test using it - what do you think?

**Comment by SylvainCorlay** [comment]
That sounds like a great suggestion.
